Repository umc-7th-hack-team-n/Server, pull requests merged in 2025-01, with the labels that each got.

#4 ✨ Feat: Add monthly conflict API
  src/controllers/conflict.controller.js
  src/db.config.js
  src/dtos/conflict.dto.js
  src/errors/conflict.error.js
  src/index.js
  src/logger.js
  src/repositories/conflict.repository.js
  src/services/conflict.service.js
Labels: :sparkles: feature

#6 ✨ feat: Add #5 specific-conflict-api
  src/controllers/conflict.controller.js
  src/dtos/conflict.dto.js
  src/errors/conflict.error.js
  src/index.js
  src/repositories/conflict.repository.js
  src/services/conflict.service.js
Labels: :sparkles: feature

#8 🗃️ Refactor: Reconstruct Promise table
  prisma/schema.prisma
Labels: :recycle: refactor

#10 Feat/#9 get promise api
  prisma/schema.prisma
  src/controllers/promise.controller.js
  src/dtos/promise.dto.js
  src/errors/promise.error.js
  src/index.js
  src/repositories/promise.repository.js
  src/services/promise.service.js
Labels: :sparkles: feature

#14 ✨ feat: Add put-promise-api
  src/controllers/promise.controller.js
  src/index.js
  src/repositories/promise.repository.js
  src/services/promise.service.js
Labels: :sparkles: feature

#16 Develop
  package-lock.json
  package.json
  prisma/schema.prisma
  src/controllers/conflict.controller.js
  src/controllers/promise.controller.js
  src/db.config.js
  src/dtos/conflict.dto.js
  src/dtos/promise.dto.js
  src/errors/conflict.error.js
  src/errors/promise.error.js
  src/index.js
  src/logger.js
  src/repositories/conflict.repository.js
  src/repositories/promise.repository.js
  src/services/conflict.service.js
  src/services/promise.service.js
Labels: :sparkles: feature

#19 🐛 bug: fix swagger annotation bug
  src/controllers/conflict.controller.js
  src/controllers/couple.controller.js
  src/controllers/promise.controller.js
  src/db.config.js
  src/dtos/conflict.dto.js
  src/dtos/couple.dto.js
  src/errors/conflict.error.js
  src/errors/couple.error.js
  src/index.js
  src/repositories/conflict.repository.js
  src/repositories/couple.repositories.js
  src/repositories/couple.repository.js
  src/services/conflict.service.js
  src/services/couple.service.js
Labels: :bug: bug

#20 Swagger test complete
  src/controllers/conflict.controller.js
  src/controllers/couple.controller.js
  src/controllers/promise.controller.js
  src/db.config.js
  src/dtos/conflict.dto.js
  src/dtos/couple.dto.js
  src/errors/conflict.error.js
  src/errors/couple.error.js
  src/index.js
  src/repositories/conflict.repository.js
  src/repositories/couple.repositories.js
  src/repositories/couple.repository.js
  src/services/conflict.service.js
  src/services/couple.service.js
Labels: :sparkles: feature

#24 bug: fix update couple api
  src/controllers/couple.controller.js
  src/services/conflict.service.js
Labels: :bug: bug
